import CarteEvent from "./CarteEvent";

const Evenements = () => {

  return (
    <div className="grid lg:grid-cols-3 gap-8 m-8">
      <div><CarteEvent titre="Evenement" desc="Nulli vera modum res amicorum prorsus ad trium multa sunt numquam precari ab honestissime non satis non quibus amicum sit detrahique invehi quibus est multa boni in rebus in amicorum indigno causa commodis rebus potius est suis multaeque sunt." img="beatbox.jpg" date="28 janvier 2026"/></div>
      <div><CarteEvent titre="Evenement" desc="Nulli vera modum res amicorum prorsus ad trium multa sunt non vera animatus aliquem faceremus Nec boni amicorum in honestissime amicorum sunt prima nostra multaeque in rebus facimus in assentior honestissime nulli illa insectarique vehementius amicorum Quam Nec ab assentior assentior fruantur ut aliquem suis quibus commodis amicum in indigno Nec amicum in enim commodis trium causa enim ab ut ipsi quae Quam in assentior multaeque in fruantur Nec trium sit numquam precari ab honestissime non satis non quibus amicum sit detrahique invehi quibus est multa boni in rebus in amicorum indigno causa commodis rebus potius est suis multaeque sunt." img="beatbox.jpg" date="28 janvier 2026"/></div>
      <div><CarteEvent titre="Evenement" desc="Nulli vera modum res amicorum prorsus ad trium multa sunt non vera animatus aliquem faceremus Nec boni amicorum in honestissime amicorum sunt prima nostra multaeque in rebus facimus in assentior honestissime nulli illa insectarique vehementius amicorum Quam Nec ab assentior assentior fruantur ut aliquem suis quibus commodis amicum in indigno Nec amicum in enim commodis trium causa enim ab ut ipsi quae Quam in assentior multaeque in fruantur Nec trium sit numquam precari ab honestissime non satis non quibus amicum sit detrahique invehi quibus est multa boni in rebus in amicorum indigno causa commodis rebus potius est suis multaeque sunt." img="beatbox.jpg" date="28 janvier 2026"/></div>
      <div><CarteEvent titre="Evenement" desc="Nulli vera modum res amicorum prorsus ad trium multa sunt non vera animatus aliquem faceremus Nec boni amicorum in honestissime amicorum sunt prima nostra multaeque in rebus facimus in assentior honestissime nulli illa insectarique vehementius amicorum Quam Nec ab assentior assentior fruantur ut aliquem suis quibus commodis amicum in indigno Nec amicum in enim commodis trium causa enim ab ut ipsi quae Quam in assentior multaeque in fruantur Nec trium sit numquam precari ab honestissime non satis non quibus amicum sit detrahique invehi quibus est multa boni in rebus in amicorum indigno causa commodis rebus potius est suis multaeque sunt." img="beatbox.jpg" date="28 janvier 2026"/></div>
      <div><CarteEvent titre="Evenement" desc="Nulli vera modum res amicorum prorsus ad trium multa sunt non vera animatus aliquem faceremus Nec boni amicorum in honestissime amicorum sunt prima nostra multaeque in rebus facimus in assentior honestissime nulli illa insectarique vehementius amicorum Quam Nec ab assentior assentior fruantur ut aliquem suis quibus commodis amicum in indigno Nec amicum in enim commodis trium causa enim ab ut ipsi quae Quam in assentior multaeque in fruantur Nec trium sit numquam precari ab honestissime non satis non quibus amicum sit detrahique invehi quibus est multa boni in rebus in amicorum indigno causa commodis rebus potius est suis multaeque sunt." img="beatbox.jpg" date="28 janvier 2026"/></div>
    </div>
  );
}

export default Evenements;
